apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-nginx
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: dev-nginx
        image: nginx
        env:
        - name: "TZ"
          value: "Asia/Singapore"