apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: nginx
          image: nginx
          env:
            - name: "TZ"
              value: "Asia/Singapore"
            - name: TOKEN
              valueFrom:
                secretKeyRef:
                  name: secret-to-be-created
                  key: TOKEN
          volumeMounts:
            - name: dev-nginx-conf
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
            - name: dev-proxy-conf
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: nginx.conf
            - name: dev-nginx-api-conf
              mountPath: /etc/nginx/conf.d/cons_conf.d
            - name: dev-nginx-path-conf
              mountPath: /etc/nginx/conf.d/path_conf.d
      volumes:
        - name: dev-nginx-conf
          configMap:
            name: dev-nginx-conf
            items:
              - key: nginx.conf
                path: nginx.conf
        - name: dev-proxy-conf
          configMap:
            name: dev-proxy-conf
            items:
              - key: nginx.conf
                path: nginx.conf
        - name: dev-nginx-api-conf
          configMap:
            name: dev-nginx-api-conf
        - name: dev-nginx-path-conf
          configMap:
            name: dev-nginx-path-conf    