apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: nginx
          image: nginx
          env:
            - name: "TZ"
              value: "Asia/Singapore"
            - name: TOKEN
              valueFrom:
                secretKeyRef:
                  name: secret-to-be-created
                  key: token
          volumeMounts:
            - name: dev-nginx-conf
              mountPath: /etc/nginx/nginx.conf
              # subPath: nginx.conf
      volumes:
        - name: dev-nginx-conf
          configMap:
            name: dev-nginx-conf
            items:
              - key: nginx.conf
                path: nginx.conf