apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-nginx
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    # alb.ingress.kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}]'
    alb.ingress.kubernetes.io/load-balancer-name: ingress
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/tags: |
        Cost Center=ISGM1-G1,
        Cloud Environment=AWS,
        Data Classification=CONFIDENTIAL-PERSONAL,
        Deployment=SB:PREP,
        Platform Name=Sandbox,
        Project=CapBuild,
        WBS Code=NA,
        EC2-Backup-Daily=FALSE,
        EC2-Backup-Weekly=FALSE,
        EC2-Backup-Monthly=FALSE
        
  labels:
    app: nginx-ingress
    env: dev
spec:
  ingressClassName: alb
  defaultBackend:
    service:
      name: dev-nginx-svc
      port:
        number: 80
  rules:
    - http:
        paths:
        - backend:
            service:
              name: dev-nginx-svc
              port:
                number: 80
          path: /
          pathType: Prefix
