apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: dev-

resources:
  - ../../base
  - secret-store.yaml
  - secrets.yaml

patches:
  - path: deployment.yaml
    target: 
      kind: Deployment


configMapGenerator:
  - files:
      - nginx/nginx.conf
    name: nginx-conf

generatorOptions:
  disableNameSuffixHash: true