apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: dev-

resources:
  - ../../base
  - secret-store.yaml
  - secrets.yaml
  - ingress.yaml

patches:
  - path: deployment.yaml
    target: 
      kind: Deployment


configMapGenerator:
  - name: nginx-conf
    files:
      - nginx/nginx.conf
  - name: proxy-conf
    files:
      - proxy/nginx.conf
  - name: nginx-api-conf
    files:
      - api-conf/cxs_auth.conf
      - api-conf/cxs.conf    
  - name: nginx-path-conf
    files:
      - api-path/generate-uuid.conf
      - api-path/argocd.conf

generatorOptions:
  disableNameSuffixHash: true