apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: dev-

resources:
  - ../../base
  - secret-store.yaml
  - secrets.yaml

patches:
  - path: deployment.yaml
    target: 
      kind: Deployment


configMapGenerator:
  - name: nginx-conf
    files:
      - nginx/nginx.conf
  - name: proxy-conf
    files:
      - proxy/app.conf  

generatorOptions:
  disableNameSuffixHash: true