apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: secrets
spec:
  refreshInterval: 30m                                 # rate SecretManager pulls
  secretStoreRef:
    name: dev-secretstore                              # name of the SecretStore wherein auths creds to be use
    kind: SecretStore
  target:
    name: secret-to-be-created                         # name of the k8s secret to be created 
    creationPolicy: Owner
  data:
    - secretKey: TOKEN                               # DEST - name of the key in the k8s secret that will be mapped to
      remoteRef:
        key: dev/app/token                           # SOURCE - AWS SecretManager secret's name.
        # version: v1
        property: token
  # dataFrom:
  # - extract:
  #     key:  dev/app/token                               # AWS SecretManager secret's name.