apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: app-secrets
spec:
  refreshInterval: 30m                               # rate SecretManager pulls
  secretStoreRef:
    name: dev-secretstore                            # name of the SecretStore # or ClusterSecretStore wherein auths session creds to be use
    kind: SecretStore
  target:
    name: secret-to-be-created                       # DEST - name of the k8s secret (TO BE CREATED) 
    creationPolicy: Owner
  data:
    - secretKey: TOKEN                               # DEST - name of the key in the k8s secret that will be mapped to
      remoteRef:
        key: dev/app/token                           # SOURCE - AWS SecretManager secret's name.
        property: token                              # SOURCE - AWS SecretManager secret attribute's property
        # version: v1
  # dataFrom:
  # - extract:
  #     key:  dev/app/token                          # SOURCE - AWS SecretManager secret's name.