apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: secrets
spec:
  refreshInterval: 1m                                 # rate SecretManager pulls
  secretStoreRef:
    name: dev-secretstore                             # name of the SecretStore
    kind: SecretStore
  target:
    name: secret-to-be-created                      # name of the k8s secret that will be mapped to
    creationPolicy: Owner
  # data:
  #   - secretKey: token                                # DEST - name of the key in the k8s secret that will be mapped to
  #     remoteRef:
  #       key: dev/app/token                             # SOURCE - name of the aws secret
  #       version: v1
  #       property: provider-key-property
  dataFrom:
  - extract:
      key:  dev/app/token