apiVersion: apps/v1
kind: Deployment
metadata:
  name: mdk-dplymnt
spec:
  replicas: 1
  revisionHistoryLimit: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 0
  selector:
    matchLabels:
      name: mdk
  template:
    metadata:
      labels:
        name: mdk
    spec:
      containers:
        - image: butch/mdk:v1
          name: mdk
          ports:
            - containerPort: 8080
          env:
            - name: "TZ"
              value: "Asia/Singapore"
